### ISSUE TITLE
Feature request : show HUD not on hover but constantly as long as a token is selected

### ISSUE THREAD

**Issue by roi007leaf** [reonZ/pf2e-token-hud#1]
Title, basically like token action hud does it.
Love the module!

**Comment by reonZ** [comment]
Despite its name, the module is actually an interactive tooltip, you don't need the token to be selected at all to use it, i may look into that eventually but nothing was prepared for that during development and this would be very low priority.

**Comment by roi007leaf** [comment]
What happens when I as a gm need the foundry token hud though? It makes the token action hud disappear, and you have to open those menus again

**Comment by reonZ** [comment]
There is no reason to have both hud at the same time, they wouldn't coexist well anyways because they would overlap with each other.

The module makes sure that when you want to do something else than interacting with the tooltip, you can do it without interference from it, so if you click on the screen anywhere to select a token, drag & drop a token, opening a token foundry hud, the tooltip just vanishes.

It was never meant to be a "constantly on screen" kind of thing but a fast way to have a glance at actors' infos and be able to use the most common actor's features without having to constantly opening and closing big sheets on screen.

**Comment by roi007leaf** [comment]
Gotcha. Fair.
