### ISSUE TITLE
Icons for Strikes

### ISSUE THREAD

**Issue by Carlosjrlu** [reonZ/pf2e-token-hud#17]
Would it be possible to have the weapon icons from the character sheet appear in the strikes sidebar?

Something like this:
![image](https://github.com/reonZ/pf2e-token-hud/assets/20954701/6c789674-d76c-4f62-8764-474c90b6799f)

**Comment by reonZ** [comment]
I originally added them but the real estate on strikes is very very tight, on your screen you are showing the best case scenario but there are strikes that, with the current layout (without icon) can end up spanning across 3-4 lines because of the amount of things to display.

So i decided against having the icon. 

I know that most people would be fine with a larger sidebar but the original idea of the module was to look like it does right now, i already made a few exceptions but i really prefer to not stray from the original design.

**Comment by Carlosjrlu** [comment]
Maybe we could have a (default disabled) option so people could have it for lower levels, and disable it when it gets too convoluted.
I think it would be really cool for newer players to see the image there.
